name: GuBu-Batch CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['GuBu-Batch CI']
    types: [completed]
    branches: [main]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Ubuntu
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PEMKEY }}
          port: ${{ secrets.SERVER_SSH }}
          script: |
            # Load nvm and node environment
            export NVM_DIR="/home/ubuntu/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            cd /home/ubuntu/8JO/gubu_batch

            pm2 delete gubu-batch || true

            rm -rf dist/

            tar -xzf gubu-batch.tar.gz

            echo "${{ secrets.SERVER_ENV }}" | base64 -d > .env

            pm2 start bundle.js --name gubu-batch

            rm gubu-batch.tar.gz

            pm2 save
